version: '3'
services:
  mattermost-db:
    environment:
      - DATADIR=/var/lib/mysql
      - MYSQL_ROOT_PASSWORD=mattermost
      - MYSQL_DATABASE=mattermost
      - MYSQL_USER=mattermost
      - MYSQL_PASSWORD=mattermost
      - TZ=Asia/Tokyo
    image: learnin/mattermost-db
    ports:
      - "50102:3306"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mattermost-db-data:/var/lib/mysql
  mattermost-app:
    depends_on:
      - mattermost-db
    environment:
      - DB_HOST=db
      - DB_PORT_5432_TCP_PORT=3306
      - MM_DBNAME=mattermost
      - MM_USERNAME=mattermost
      - MM_PASSWORD=mattermost
      - TZ=Asia/Tokyo
    image: learnin/mattermost-app
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mattermost-app-config:/mattermost/config
      - mattermost-app-data:/mattermost/data
  mattermost-web:
    depends_on:
      - mattermost-app
    environment:
      - MATTERMOST_ENABLE_SSL=false
      - PLATFORM_PORT_80_TCP_PORT=80
      - TZ=Asia/Tokyo
    image: learnin/mattermost-web
    ports:
      - "50002:80"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
  gitbucket-db:
    environment:
      - DATADIR=/var/lib/mysql
      - MYSQL_ROOT_PASSWORD=gitbucket
      - MYSQL_DATABASE=gitbucket
      - MYSQL_USER=gitbucket
      - MYSQL_PASSWORD=gitbucket
      - TZ=Asia/Tokyo
    image: learnin/gitbucket-db
    ports:
      - "50103:3306"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gitbucket-db-data:/var/lib/mysql
  gitbucket-app:
    depends_on:
      - gitbucket-db
    environment:
      - GITBUCKET_DB_HOST=db
      - GITBUCKET_DB_NAME=gitbucket
      - GITBUCKET_DB_USER=gitbucket
      - GITBUCKET_DB_PASSWORD=gitbucket
      - JAVA_OPTS=-server
      - GITBUCKET_OPTS=--port=80
      - TZ=Asia/Tokyo
    image: learnin/gitbucket-app
    ports:
      - "50003:80"
      - "29418:29418"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gitbucket-app-data:/gitbucket
  hubot-mattermost:
    environment:
      - MATTERMOST_HOST=${MATTERMOST_HOST}
      - MATTERMOST_GROUP=${MATTERMOST_GROUP}
      - MATTERMOST_USER=${MATTERMOST_USER}
      - MATTERMOST_PASSWORD=${MATTERMOST_PASSWORD}
      - MATTERMOST_HTTP_PORT=${MATTERMOST_HTTP_PORT}
      - MATTERMOST_WSS_PORT=${MATTERMOST_WSS_PORT}
      - MATTERMOST_TLS_VERIFY=${MATTERMOST_TLS_VERIFY}
      - MATTERMOST_USE_TLS=${MATTERMOST_USE_TLS}
      - HUBOT_JENKINS_URL=${HUBOT_JENKINS_URL}
      - HUBOT_JENKINS_AUTH=${HUBOT_JENKINS_AUTH}
      - TZ=Asia/Tokyo
    image: learnin/hubot-mattermost
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - hubot-mattermost-data:/home/hubot
  jenkins:
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
      - TZ=Asia/Tokyo
    image: learnin/jenkins
    ports:
      - "50000:50000"
      - "50001:8080"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jenkins-data:/var/jenkins_home
  redmine-db:
    environment:
      - DATADIR=/var/lib/mysql
      - MYSQL_ROOT_PASSWORD=redmine
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmine
      - TZ=Asia/Tokyo
    image: learnin/redmine-db
    ports:
      - "50104:3306"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redmine-db-data:/var/lib/mysql
  redmine-app:
    depends_on:
      - redmine-db
    environment:
      - REDMINE_DB_MYSQL=db
      - MYSQL_ENV_MYSQL_USER=redmine
      - MYSQL_ENV_MYSQL_PASSWORD=redmine
      - MYSQL_ENV_MYSQL_DATABASE=redmine
      - REDMINE_DB_ENCODING=utf8mb4
      - TZ=Asia/Tokyo
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
    image: redmine:3.3.2-passenger
    ports:
      - "50004:3000"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redmine-app-data:/usr/src/redmine/files
volumes:
  mattermost-db-data: {}
  mattermost-app-config: {}
  mattermost-app-data: {}
  gitbucket-db-data: {}
  gitbucket-app-data: {}
  hubot-mattermost-data: {}
  jenkins-data: {}
  redmine-db-data: {}
  redmine-app-data: {}
